version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - gis_3ban_network
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
      - kalrasu_static:/data/static/
      - kalrasu_media:/data/media/

  django:
    image: kalrasu_django:4
    networks:
      - gis_3ban_network
    volumes:
      - kalrasu_static:/home/kalrasu/staticfiles/
      - kalrasu_media:/home/kalrasu/media/

  mariadb:
    image: mariadb:10.5
    networks:
      - gis_3ban_network
    volumes:
      - kalrasu_mariadb:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: password1234
      MARIADB_DATABASE: django
      MARIADB_USER: django
      MARIADB_PASSWORD: password1234


networks:
  gis_3ban_network:

volumes:
  kalrasu_static:
  kalrasu_media:
  kalrasu_mariadb:
