version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - gis_3ban_network
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
      - kalrasu_static:/data/static/
      - kalrasu_media:/data/media/

  django:
    image: kalrasu_django:5
    networks:
      - gis_3ban_network
    volumes:
      - kalrasu_static:/home/kalrasu/staticfiles/
      - kalrasu_media:/home/kalrasu/media/
    secrets:
      - kalrasu_DJANGO_SECRET_KEY
      - MARIADB_USER
      - MARIADB_PASSWORD

  mariadb:
    image: mariadb:10.5
    networks:
      - gis_3ban_network
    volumes:
      - kalrasu_mariadb:/var/lib/mysql
    secrets:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_USER
      - MARIADB_PASSWORD
    environment:
      MARIADB_DATABASE: django
      MARIADB_USER_FILE: /run/secrets/MARIADB_USER
      MARIADB_PASSWORD_FILE: /run/secrets/MARIADB_PASSWORD
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/MARIADB_ROOT_PASSWORD


networks:z
  gis_3ban_network:

volumes:
  kalrasu_static:
  kalrasu_media:
  kalrasu_mariadb:

secrets:
  kalrasu_DJANGO_SECRET_KEY:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true
  MARIADB_USER:
    external: true
  MARIADB_PASSWORD:
    external: true