version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - gis_3ban_network
    volumes:
      - /home/ubuntu/nginx.conf:etc/nginx/nginx.conf
      - kalrasu_static:/data/static/
      - kalrasu_media:/data/media/

  django:
    image: kalrasu_django:3
    network:
      - gis_3ban_network
    volumes:
      - kalrasu_static:/home/kalrasu/staticfiles/
      - kalrasu_media:/home/kalrasu/media/

networks:
  gis_3ban_network:

volumes:
  kalrasu_static:
  kalrasu_media:
